apiVersion: "nuclio.io/v1"
kind: Function
metadata: 
  name: mqtt-fuelconsumer
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "Function that receives data from sensors of incoming planes and dispathces messages on other topics"
  runtime: nodejs
  image: "nuclio/mqtt-fuel-consumer:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  triggers:
    myMqttTrigger:
      kind: "mqtt"
      url: "user:password@192.168.1.7:1883"
      attributes:
        subscriptions:
        - topic: iot/planes/arrivals/fuel
          qos: 0
  build:
    functionSourceCode: dmFyIGFtcXAgPSByZXF1aXJlKCdhbXFwbGliJyk7Ci8vbnBtIHBhY2thZ2UgdG8gbWFuYWdlIGFpcnBsYW5lcwp2YXIgUGxhbmUgPSByZXF1aXJlKCdwbGFuZXMtZ2VuZXJhdG9yJyk7Ci8vbnBtIHBhY2thZ2UgdG8gbWFuYWdlIElGVFRUIGludm9jYXRpb24KdmFyIElGVFRUID0gcmVxdWlyZSgnaWZ0dHQtd2ViaG9va3MtY2hhbm5lbCcpOwpjb25zdCBpZnR0dCA9IG5ldyBJRlRUVCgnbkFtSUw3VzQ1T2VFYllyRjhPMEx5dFlhdXA3WWRVNVJFZ1JuS1l0TmRVcCcpOwoKLy8gVGhpcyBmdW5jdGlvbiBzZW5kcyBtZXNzYWdlcyB0byB0aGUgZnVlbF9sb2dnZXIgb24gdGhlIGFtcXAgdG9waWMgbG9ncy9hcnJpdmFscy9mdWVsCmZ1bmN0aW9uIHNlbmRfZmVlZGJhY2sobXNnKXsKICAgIHZhciBxID0gJ2xvZ3MvYXJyaXZhbHMvZnVlbCc7CiAgICBhbXFwLmNvbm5lY3QoJ2FtcXA6Ly9ndWVzdDpndWVzdEAxOTIuMTY4LjEuNzo1NjcyJykudGhlbihmdW5jdGlvbihjb25uKSB7CiAgICAgIHJldHVybiBjb25uLmNyZWF0ZUNoYW5uZWwoKS50aGVuKGZ1bmN0aW9uKGNoKSB7CiAgICAgICAgdmFyIG9rID0gY2guYXNzZXJ0UXVldWUocSwge2R1cmFibGU6IGZhbHNlfSk7CiAgICAgICAgcmV0dXJuIG9rLnRoZW4oZnVuY3Rpb24oX3FvaykgewogICAgICAgICAgY2guc2VuZFRvUXVldWUocSwgQnVmZmVyLmZyb20obXNnKSk7CiAgICAgICAgICBjb25zb2xlLmxvZygiIFt4XSBTZW50ICclcyciLCBtc2cpOwogICAgICAgICAgcmV0dXJuIGNoLmNsb3NlKCk7CiAgICAgICAgfSk7CiAgICAgIH0pLmZpbmFsbHkoZnVuY3Rpb24oKSB7CiAgICAgICAgY29ubi5jbG9zZSgpOwogICAgICB9KTsKICAgIH0pLmNhdGNoKGNvbnNvbGUud2Fybik7Cn0KCi8vIFRoaXMgZnVuY3Rpb24gY2F0Y2hzIHRoZSBldmVudCBmcm9tIHRoZSBtcXR0TWVzc2FnZURpc3BhdGNoZXIgZXZlcnkgdGltZSBhIHBsYW5lIGxhbmRzCmV4cG9ydHMuaGFuZGxlciA9IGZ1bmN0aW9uKGNvbnRleHQsIGV2ZW50KSB7CiAgICB2YXIgX2V2ZW50ID0gSlNPTi5wYXJzZShKU09OLnN0cmluZ2lmeShldmVudCkpOwogICAgLy8gcmVjcmVhdGUgdGhlIHBsYW5lIHJlY2VpdmVkIGFzIGV2ZW50CiAgICB2YXIgY3VycmVudFBsYW5lID0gbmV3IFBsYW5lKF9ldmVudC5ib2R5LmRhdGEpOwogICAgdmFyIGRhdGUgPSBuZXcgRGF0ZSgpOyAgICAgICAKICAgICAgCiAgICBjb250ZXh0LmNhbGxiYWNrKCJmZWVkYmFjayAiKTsKICAgIAogICAgLy8gd3JpdGUgb24gdGhlIGZ1ZWxfbG9nZ2VyCiAgICBzZW5kX2ZlZWRiYWNrKGN1cnJlbnRQbGFuZS5tb2RlbCArICIgIiArIGN1cnJlbnRQbGFuZS5uYW1lICsgIiBpcyAiICsgY3VycmVudFBsYW5lLnRhZyArICIgd2l0aCAiICsgY3VycmVudFBsYW5lLmZ1ZWxMZXZlbCArICIlIG9mIGZ1ZWwuIEZ1ZWwgbmVlZGluZyBjb21wdXRlZDogIiArIGN1cnJlbnRQbGFuZS5jb21wdXRlUmVmdWVsKCkgKyAiIGxpdGVycyEiKTsKCiAgICAvLyBpbnZva2UgdGhlIHdlYmhvb2sKICAgIGlmdHR0LnBvc3QoJ3BsYW5lX3JlZnVlbGluZycsIFtjdXJyZW50UGxhbmUubW9kZWwgKyAiIC0gIiArIGN1cnJlbnRQbGFuZS5uYW1lLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRlLmdldERhdGUoKSArICIvIiArIChkYXRlLmdldE1vbnRoKCkrMSkgKyAiLyIgKyBkYXRlLmdldEZ1bGxZZWFyKCkgKyAiIC0gIiArIChkYXRlLmdldEhvdXJzKCkrMSkgKyAiOiIgKyBkYXRlLmdldE1pbnV0ZXMoKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjdXJyZW50UGxhbmUuY29tcHV0ZVJlZnVlbCgpICsgIiBsaXRlcnMiXSk7CiAgfTs=
    commands:
      - 'npm install amqplib'
      - 'npm i planes-generator'
      - 'npm i ifttt-webhooks-channel'
    codeEntryType: sourceCode
  platform: {} 