apiVersion: "nuclio.io/v1"
kind: Function
metadata: 
  name: mqtt-issueconsumer
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "Function that receives data from sensors of incoming planes and dispathces messages on other topics"
  runtime: nodejs
  image: "nuclio/mqtt-issue-consumer:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  triggers:
    myMqttTrigger:
      kind: "mqtt"
      url: "user:password@192.168.1.7:1883"
      attributes:
        subscriptions:
        - topic: iot/planes/arrivals/issues
        qos: 0
  build:
    functionSourceCode: dmFyIGFtcXAgPSByZXF1aXJlKCdhbXFwbGliJyk7Ci8vbnBtIHBhY2thZ2UgdG8gbWFuYWdlIGFpcnBsYW5lcwp2YXIgUGxhbmUgPSByZXF1aXJlKCdwbGFuZXMtZ2VuZXJhdG9yJyk7Ci8vbnBtIHBhY2thZ2UgdG8gbWFuYWdlIElGVFRUIGludm9jYXRpb24KdmFyIElGVFRUID0gcmVxdWlyZSgnaWZ0dHQtd2ViaG9va3MtY2hhbm5lbCcpOwpjb25zdCBpZnR0dCA9IG5ldyBJRlRUVCgnbkFtSUw3VzQ1T2VFYllyRjhPMEx5dFlhdXA3WWRVNVJFZ1JuS1l0TmRVcCcpOwoKLy8gVGhpcyBmdW5jdGlvbiBzZW5kcyBtZXNzYWdlcyB0byB0aGUgaXNzdWVfbG9nZ2VyIG9uIHRoZSBhbXFwIHRvcGljIGxvZ3MvYXJyaXZhbHMvaXNzdWVzCmZ1bmN0aW9uIHNlbmRfZmVlZGJhY2sobXNnKXsKICAgIHZhciBxID0gJ2xvZ3MvYXJyaXZhbHMvaXNzdWVzJzsKICAgIGFtcXAuY29ubmVjdCgnYW1xcDovL2d1ZXN0Omd1ZXN0QDE5Mi4xNjguMS43OjU2NzInKS50aGVuKGZ1bmN0aW9uKGNvbm4pIHsKICAgICAgcmV0dXJuIGNvbm4uY3JlYXRlQ2hhbm5lbCgpLnRoZW4oZnVuY3Rpb24oY2gpIHsKICAgICAgICB2YXIgb2sgPSBjaC5hc3NlcnRRdWV1ZShxLCB7ZHVyYWJsZTogZmFsc2V9KTsKICAgICAgICByZXR1cm4gb2sudGhlbihmdW5jdGlvbihfcW9rKSB7CiAgICAgICAgICBjaC5zZW5kVG9RdWV1ZShxLCBCdWZmZXIuZnJvbShtc2cpKTsKICAgICAgICAgIGNvbnNvbGUubG9nKCIgW3hdIFNlbnQgJyVzJyIsIG1zZyk7CiAgICAgICAgICByZXR1cm4gY2guY2xvc2UoKTsKICAgICAgICB9KTsKICAgICAgfSkuZmluYWxseShmdW5jdGlvbigpIHsKICAgICAgICBjb25uLmNsb3NlKCk7CiAgICAgIH0pOwogICAgfSkuY2F0Y2goY29uc29sZS53YXJuKTsKfQoKLy8gVGhpcyBmdW5jdGlvbiBjYXRjaHMgdGhlIGV2ZW50IGZyb20gdGhlIG1xdHRNZXNzYWdlRGlzcGF0Y2hlciBldmVyeSB0aW1lIGEgcGxhbmUgbGFuZHMKZXhwb3J0cy5oYW5kbGVyID0gZnVuY3Rpb24oY29udGV4dCwgZXZlbnQpIHsKICAgIHZhciBfZXZlbnQgPSBKU09OLnBhcnNlKEpTT04uc3RyaW5naWZ5KGV2ZW50KSk7CiAgICAvLyByZWNyZWF0ZSB0aGUgcGxhbmUgcmVjZWl2ZWQgYXMgZXZlbnQKICAgIHZhciBjdXJyZW50UGxhbmUgPSBuZXcgUGxhbmUoX2V2ZW50LmJvZHkuZGF0YSk7CiAgICB2YXIgZGF0ZSA9IG5ldyBEYXRlKCk7ICAgICAgIAogIAogICAgY29udGV4dC5jYWxsYmFjaygiZmVlZGJhY2sgIik7CiAgICAKICAgIC8vIHdyaXRlIG9uIHRoZSBpc3N1ZSBsb2dnZXIKICAgIHNlbmRfZmVlZGJhY2soY3VycmVudFBsYW5lLm1vZGVsICsgIiAiICsgY3VycmVudFBsYW5lLm5hbWUgKyAiIGlzICIgKyBjdXJyZW50UGxhbmUudGFnICsgIiEgVGhlIHNlbnNvcnMgZW5jb3VudGVyZWQgYSAiICsgY3VycmVudFBsYW5lLmNhc3VhbElzc3VlKTsKCiAgICAvLyBpbnZva2UgdGhlIHdlYmhvb2sKICAgIGlmdHR0LnBvc3QoJ3BsYW5lX21hbGZ1bmN0aW9uJywgW2N1cnJlbnRQbGFuZS5tb2RlbCArICIgLSAiICsgY3VycmVudFBsYW5lLm5hbWUsIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGUuZ2V0RGF0ZSgpICsgIi8iICsgKGRhdGUuZ2V0TW9udGgoKSsxKSArICIvIiArIGRhdGUuZ2V0RnVsbFllYXIoKSArICIgLSAiICsgKGRhdGUuZ2V0SG91cnMoKSsxKSArICI6IiArIGRhdGUuZ2V0TWludXRlcygpLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgY3VycmVudFBsYW5lLmNhc3VhbElzc3VlXSk7CiAgfTs=
    commands:
      - 'npm install amqplib'
      - 'npm i planes-generator'
      - 'npm i ifttt-webhooks-channel'
    codeEntryType: sourceCode
  platform: {} 